# Примеры неправильного применения критерия Манна-Уитни

In [1]:
import numpy as np
from scipy.stats import mannwhitneyu

## Пример 1. Проверка гипотезы равенства средних

In [2]:
rng = np.random.default_rng(42)
x = rng.gamma(shape=1, scale=1000, size=100)
x

array([2404.20860397, 2336.18965582, 2384.76099987,  279.79428985,
         86.4373997 , 1452.66051571, 1409.96069426, 3124.29595655,
         79.29419718, 1046.56084654,   70.4363068 , 1089.02362802,
       1731.32735288,  386.89482459, 1231.58566266,  153.77325383,
         91.57726739,  315.17920213,  901.19927537,  412.98532974,
       1247.38594981,  223.57637221, 1837.97026414, 1227.08586321,
        655.79615396,  417.08670631,  453.3196893 ,   77.07714706,
        179.63225437,  685.3204516 ,  388.68023616, 1264.20685757,
        708.49062742,  237.9299543 ,  461.08833626,  641.55673719,
        343.83336144,  321.91122091,  878.91468219,  296.94720893,
       1333.70242503, 1390.86398625, 1084.08292797,   73.02834798,
       1134.06750172, 1354.33798787, 1122.03965146,  280.04912024,
        320.93619104,  165.7359073 ,  354.36351269,   21.13975641,
        167.35639612, 1315.05684455, 3995.75627118,  563.53809239,
        284.0397016 ,  397.75625391,  361.34222293,  129.63360

In [3]:
y = np.arange(np.mean(x) - 0.495, np.mean(x) + 0.505, 0.01)
y

array([898.55889334, 898.56889334, 898.57889334, 898.58889334,
       898.59889334, 898.60889334, 898.61889334, 898.62889334,
       898.63889334, 898.64889334, 898.65889334, 898.66889334,
       898.67889334, 898.68889334, 898.69889334, 898.70889334,
       898.71889334, 898.72889334, 898.73889334, 898.74889334,
       898.75889334, 898.76889334, 898.77889334, 898.78889334,
       898.79889334, 898.80889334, 898.81889334, 898.82889334,
       898.83889334, 898.84889334, 898.85889334, 898.86889334,
       898.87889334, 898.88889334, 898.89889334, 898.90889334,
       898.91889334, 898.92889334, 898.93889334, 898.94889334,
       898.95889334, 898.96889334, 898.97889334, 898.98889334,
       898.99889334, 899.00889334, 899.01889334, 899.02889334,
       899.03889334, 899.04889334, 899.05889334, 899.06889334,
       899.07889334, 899.08889334, 899.09889334, 899.10889334,
       899.11889334, 899.12889334, 899.13889334, 899.14889334,
       899.15889334, 899.16889334, 899.17889334, 899.18

In [4]:
print(f'Средние равны: {np.mean(x)} = {np.mean(y)}')
print(f'А тест "прокрашивается": {mannwhitneyu(x, y)}')

Средние равны: 899.0538933419094 = 899.053893341909
А тест "прокрашивается": MannwhitneyuResult(statistic=4200.0, pvalue=0.02538081514855085)


## Пример 2. Ещё одна проверка гипотезы равенства средних

In [5]:
x = np.arange(1000, 1001, 0.01)
x

array([1000.  , 1000.01, 1000.02, 1000.03, 1000.04, 1000.05, 1000.06,
       1000.07, 1000.08, 1000.09, 1000.1 , 1000.11, 1000.12, 1000.13,
       1000.14, 1000.15, 1000.16, 1000.17, 1000.18, 1000.19, 1000.2 ,
       1000.21, 1000.22, 1000.23, 1000.24, 1000.25, 1000.26, 1000.27,
       1000.28, 1000.29, 1000.3 , 1000.31, 1000.32, 1000.33, 1000.34,
       1000.35, 1000.36, 1000.37, 1000.38, 1000.39, 1000.4 , 1000.41,
       1000.42, 1000.43, 1000.44, 1000.45, 1000.46, 1000.47, 1000.48,
       1000.49, 1000.5 , 1000.51, 1000.52, 1000.53, 1000.54, 1000.55,
       1000.56, 1000.57, 1000.58, 1000.59, 1000.6 , 1000.61, 1000.62,
       1000.63, 1000.64, 1000.65, 1000.66, 1000.67, 1000.68, 1000.69,
       1000.7 , 1000.71, 1000.72, 1000.73, 1000.74, 1000.75, 1000.76,
       1000.77, 1000.78, 1000.79, 1000.8 , 1000.81, 1000.82, 1000.83,
       1000.84, 1000.85, 1000.86, 1000.87, 1000.88, 1000.89, 1000.9 ,
       1000.91, 1000.92, 1000.93, 1000.94, 1000.95, 1000.96, 1000.97,
       1000.98, 1000

In [6]:
y = np.arange(999, 1000, 0.01)
y[99] += np.sum(x) - np.sum(y)
y

array([ 999.  ,  999.01,  999.02,  999.03,  999.04,  999.05,  999.06,
        999.07,  999.08,  999.09,  999.1 ,  999.11,  999.12,  999.13,
        999.14,  999.15,  999.16,  999.17,  999.18,  999.19,  999.2 ,
        999.21,  999.22,  999.23,  999.24,  999.25,  999.26,  999.27,
        999.28,  999.29,  999.3 ,  999.31,  999.32,  999.33,  999.34,
        999.35,  999.36,  999.37,  999.38,  999.39,  999.4 ,  999.41,
        999.42,  999.43,  999.44,  999.45,  999.46,  999.47,  999.48,
        999.49,  999.5 ,  999.51,  999.52,  999.53,  999.54,  999.55,
        999.56,  999.57,  999.58,  999.59,  999.6 ,  999.61,  999.62,
        999.63,  999.64,  999.65,  999.66,  999.67,  999.68,  999.69,
        999.7 ,  999.71,  999.72,  999.73,  999.74,  999.75,  999.76,
        999.77,  999.78,  999.79,  999.8 ,  999.81,  999.82,  999.83,
        999.84,  999.85,  999.86,  999.87,  999.88,  999.89,  999.9 ,
        999.91,  999.92,  999.93,  999.94,  999.95,  999.96,  999.97,
        999.98, 1099

In [7]:
print(f'Средние равны: {np.mean(x)} = {np.mean(y)}')
print(f'А тест "прокрашивается": {mannwhitneyu(x, y)}')

Средние равны: 1000.4949999999997 = 1000.4949999999997
А тест "прокрашивается": MannwhitneyuResult(statistic=100.0, pvalue=2.50922711650892e-33)


## Пример 3. Проверка гипотезы равенства медиан

In [8]:
x = np.concatenate((
    np.arange(1000, 1000.5, 0.01),
    np.arange(1001, 1001.5, 0.01),
))
x

array([1000.  , 1000.01, 1000.02, 1000.03, 1000.04, 1000.05, 1000.06,
       1000.07, 1000.08, 1000.09, 1000.1 , 1000.11, 1000.12, 1000.13,
       1000.14, 1000.15, 1000.16, 1000.17, 1000.18, 1000.19, 1000.2 ,
       1000.21, 1000.22, 1000.23, 1000.24, 1000.25, 1000.26, 1000.27,
       1000.28, 1000.29, 1000.3 , 1000.31, 1000.32, 1000.33, 1000.34,
       1000.35, 1000.36, 1000.37, 1000.38, 1000.39, 1000.4 , 1000.41,
       1000.42, 1000.43, 1000.44, 1000.45, 1000.46, 1000.47, 1000.48,
       1000.49, 1001.  , 1001.01, 1001.02, 1001.03, 1001.04, 1001.05,
       1001.06, 1001.07, 1001.08, 1001.09, 1001.1 , 1001.11, 1001.12,
       1001.13, 1001.14, 1001.15, 1001.16, 1001.17, 1001.18, 1001.19,
       1001.2 , 1001.21, 1001.22, 1001.23, 1001.24, 1001.25, 1001.26,
       1001.27, 1001.28, 1001.29, 1001.3 , 1001.31, 1001.32, 1001.33,
       1001.34, 1001.35, 1001.36, 1001.37, 1001.38, 1001.39, 1001.4 ,
       1001.41, 1001.42, 1001.43, 1001.44, 1001.45, 1001.46, 1001.47,
       1001.48, 1001

In [9]:
y = x + 0.1
y[50] -= 0.2
y

array([1000.1 , 1000.11, 1000.12, 1000.13, 1000.14, 1000.15, 1000.16,
       1000.17, 1000.18, 1000.19, 1000.2 , 1000.21, 1000.22, 1000.23,
       1000.24, 1000.25, 1000.26, 1000.27, 1000.28, 1000.29, 1000.3 ,
       1000.31, 1000.32, 1000.33, 1000.34, 1000.35, 1000.36, 1000.37,
       1000.38, 1000.39, 1000.4 , 1000.41, 1000.42, 1000.43, 1000.44,
       1000.45, 1000.46, 1000.47, 1000.48, 1000.49, 1000.5 , 1000.51,
       1000.52, 1000.53, 1000.54, 1000.55, 1000.56, 1000.57, 1000.58,
       1000.59, 1000.9 , 1001.11, 1001.12, 1001.13, 1001.14, 1001.15,
       1001.16, 1001.17, 1001.18, 1001.19, 1001.2 , 1001.21, 1001.22,
       1001.23, 1001.24, 1001.25, 1001.26, 1001.27, 1001.28, 1001.29,
       1001.3 , 1001.31, 1001.32, 1001.33, 1001.34, 1001.35, 1001.36,
       1001.37, 1001.38, 1001.39, 1001.4 , 1001.41, 1001.42, 1001.43,
       1001.44, 1001.45, 1001.46, 1001.47, 1001.48, 1001.49, 1001.5 ,
       1001.51, 1001.52, 1001.53, 1001.54, 1001.55, 1001.56, 1001.57,
       1001.58, 1001

In [10]:
print(f'Медианы равны: {np.median(x)} = {np.median(y)}')
print(f'А тест "прокрашивается": {mannwhitneyu(x, y)}')

Медианы равны: 1000.7449999999998 = 1000.7449999999998
А тест "прокрашивается": MannwhitneyuResult(statistic=4071.0, pvalue=0.011643696085323502)
